spring:
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_S10K1WoKZWieIc1qHdc@mysql-224c8cda-samuelgh-c289.h.aivencloud.com:27829/proto_local?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_S10K1WoKZWieIc1qHdc

  flyway:
    enabled: false
    baseline-on-migrate: true